### ISSUE TITLE
Session options in env.json not used in session.go

### ISSUE THREAD

**Issue by srchulo** [blue-jay/core#6]
1. Which commit are you using?
de61a9f9730456a0c09acd4ab6609ea5ec1aa346

2. Which operating system, processor architecture, and Go version are you using (`go env`)?
Windows 10, Skylake i5 6600k, 

3. What did you do?
Set the session config values in env.json:

```
	"Session": {
    "AuthKey":"key",
    "EncryptKey":"key",
    "CSRFKey":"key",
		"Name": "sess",
		"Options": {
			"Path": "/",
			"Domain": "",
			"MaxAge": 28800,
			"Secure": false,
			"HttpOnly": true
		}
	},
```

4. What did you expect to see?
These config values used

5. What did you actually see?
The values in the config were not used

It seems like adding the line `i.store.Options = &i.Options` to the end of session.SetupConfig (before return nil) fixes it. I've been meaning to submit a pull request, but I haven't had the time to write a test yet, so I figured I would file this here in case someone else can get to it first.

**Comment by josephspurrier** [comment]
Good catch! Thanks for the info.

**Comment by srchulo** [comment]
np! Thanks for the fix :)
